import { Component } from '@angular/core';

import { TableModule } from 'primeng/table';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css'],
})
export class TableComponent {
  products = [
    {
      hash: '1',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/watch.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/available.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/green (1).png',
    },
    {
      hash: '2',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/second.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/notavailable.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/red.png',
    },
    {
      hash: '3',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/third.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/less.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/green (1).png',
    },
    {
      hash: '4',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/forth.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/available.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/green (1).png',
    },
    {
      hash: '5',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/second.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/notavailable.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/red.png',
    },
    {
      hash: '6',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/sixth.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/available.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/red.png',
    },
    {
      hash: '7',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/seven.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/Screenshot 2024-01-03 155026.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/Mask group (2).png',
    },
    {
      hash: '8',
      productname: 'شنطة سفر متميزة',
      image: '../../assets/eight.png',
      sellprice: '$3000',
      quantity: ' قطعه 30 ',
      statimg: '../../assets/less.png',
      category: 'قص الشعر',
      taxes: '%14',
      minimum: '50 قطعه',
      discount: '$200',
      sellingrate: '../../assets/red.png',
    },
  ];
}
